sudo: required

dist: bionic

language: python

python:
  - '3.6'

services:
  - docker

before_install:
  - if [[ "$BUILD" != "development" ]]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    sudo apt-get update && sudo apt-get -y install git;
    fi
  - if [[ $BUILD == "development" ]];then
    sudo apt-get update && sudo apt-get -y install docker-compose;
    fi
  - chmod u+x ./travis.py

after_success:
  - docker --version

jobs:
  include:
    - stage: "Build Frappe bench development environment (latest)"
      if: branch = develop AND type != pull_request
      script:
        - docker build -t rishira1/bench:latest -f build/bench/Dockerfile .
        - docker push rishira1/bench:latest
    - stage: "Frappe (v13-beta)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py frappe --worker --git-version 13-beta
        - ./travis.py frappe --worker --tag v13-beta --tag-only
        - ./travis.py frappe --worker --tag version-13-beta --tag-only
    - stage: "Frappe (v13-beta)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py frappe --nginx --git-version 13-beta
        - ./travis.py frappe --nginx --tag v13-beta --tag-only
        - ./travis.py frappe --nginx --tag version-13-beta --tag-only
    - stage: "Frappe (v13-beta)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py frappe --socketio --git-version 13-beta
        - ./travis.py frappe --socketio --tag v13-beta --tag-only
        - ./travis.py frappe --socketio --tag version-13-beta --tag-only
    - stage: "ERPNext (v13-beta)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py erpnext --worker --git-version 13-beta
        - ./travis.py erpnext --worker --tag v13-beta --tag-only
        - ./travis.py erpnext --worker --tag version-13-beta --tag-only
    - stage: "ERPNext (v13-beta)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py erpnext --nginx --git-version 13-beta
        - ./travis.py erpnext --nginx --tag v13-beta --tag-only
        - ./travis.py erpnext --nginx --tag version-13-beta --tag-only
    